const PREFIX = '[AIIENS Edu][AUTH]';

export function authLog(stage, detail) {
  const msg = String(stage || '').toUpperCase();
  console.log(`${PREFIX} ${msg}`, detail ?? '');
}

export const AUTH_STAGES = {
  START: 'OAUTH STARTED',
  SUCCESS: 'OAUTH SUCCESS',
  SESSION_FOUND: 'SESSION FOUND',
  PROFILE_EXISTS: 'PROFILE FOUND',
  PROFILE_NOT_FOUND: 'PROFILE MISSING',
  PROFILE_CREATED: 'PROFILE CREATED',
  PERSONAL_COMPLETE: 'PERSONAL COMPLETE',
  ACADEMIC_COMPLETE: 'ACADEMIC COMPLETE',
  REDIRECT_PERSONAL: 'REDIRECT TARGET PERSONAL INFORMATION',
  REDIRECT_ACADEMIC: 'REDIRECT TARGET ACADEMIC INFORMATION',
  REDIRECT_DASHBOARD: 'REDIRECT TARGET DASHBOARD',
  ROLE_MISMATCH: 'ROLE MISMATCH',
};
